name: 'pr-comment'
description: 'Publishes badges and coverage as a PR comment'

inputs:
  md_path:
    description: 'Path to the coverage report markdown file'
    required: false
    default: 'target/site/jacoco/coverage-report.md'

runs:
  using: "composite"
  steps:
    - name: generate pr_comment.md
      run: |
        echo "![build](https://img.shields.io/github/actions/workflow/status/dcs-b/dataframe-devops/ci.yml?branch=develop&style?style=flat&logo=github)" > pr_comment.md
        cat ${{ inputs.md_path }} >> pr_comment.md
      shell: bash

    - name: Add PR comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: pr_comment.md
