name: 'coverage-report'
description: 'Publish a coverage report summary'

inputs:
  csv_path:
    description: 'Path to the report csv file'
    required: false
    default: 'target/site/jacoco/jacoco.csv'
  min_coverage:
    description: 'Minimum coverage percentage required to pass the test'
    required: false
    default: '0'
  md_output:
    description: 'Path to the markdown file to generate'
    required: false
    default: 'target/site/jacoco/coverage-report.md'
  json_output:
    description: 'Path to the json file to generate'
    required: false
    default: 'target/site/jacoco/coverage-report.json'

runs:
  using: "composite"
  steps:
    - name: parse coverage report and generate json file
      shell: bash
      run: |
        output=$(python .github/actions/coverage-report/coverage.py ${{ inputs.csv_path }} ${{ inputs.min_coverage }} ${{ inputs.json_output }})
        OUTPUT=$(cat << EOF
        $output
        EOF
        )
        echo "OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$OUTPUT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: print table with parsed report and generate md file
      shell: bash
      run: |
        echo '### JaCoCo Coverage Report' >> $GITHUB_STEP_SUMMARY
        echo "${{ env.OUTPUT }}" >> $GITHUB_STEP_SUMMARY
        echo "${{ env.OUTPUT }}" > ${{ inputs.md_output }}
