name: 'coverage-report'
description: 'Publish a coverage report summary'

inputs:
  path:
    description: 'Path to the report csv file'
    required: false
    default: 'target/site/jacoco/jacoco.csv'
  min_coverage:
    description: 'Minimum coverage percentage required to pass the test'
    required: false
    default: '0'

runs:
  using: "composite"
  steps:
    - name: parse coverage report
      shell: bash
      run: |
        output=$(python .github/actions/coverage-report/coverage.py ${{ inputs.path }} ${{ inputs.min_coverage }})
        OUTPUT=$(cat << EOF
        $output
        EOF
        )
        echo "OUTPUT<<EOF" >> $GITHUB_ENV
        echo "$OUTPUT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: print table with parsed report
      shell: bash
      run: |
        echo '### JaCoCo Coverage Report' >> $GITHUB_STEP_SUMMARY
        echo "${{ env.OUTPUT }}" >> $GITHUB_STEP_SUMMARY
